version: '{build}'
clone_depth: 1
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  CYGWIN_MIRROR: http://cygwin.mirror.constant.com
  CACHE: C:\cache
  matrix:
  - BUILD: i686-pc-cygwin
  - BUILD: x86_64-pc-cygwin
install:
- if "%BUILD%"=="x86_64-pc-cygwin" set SETUP=setup-x86_64.exe && set CYGWIN_ROOT=C:\cygwin64
- if "%BUILD%"=="i686-pc-cygwin" set SETUP=setup-x86.exe && set CYGWIN_ROOT=C:\cygwin
- curl -fsSL https://gist.githubusercontent.com/jon-turney/0338af595313f598bfab15a0ac0df847/raw/bd0eeca6be899e7846aa988fbcf15e4e12f5f842/zp_libtool_cleanlafiles.sh -o %CYGWIN_ROOT%\etc\postinstall\zp_libtool_cleanlafiles.sh
- echo Updating Cygwin
- '%CYGWIN_ROOT%\%SETUP% -qnNdO -R %CYGWIN_ROOT% -s %CYGWIN_MIRROR% -l %CACHE% -g -P cygport,python3'
build_script:
- SET PATH=%CYGWIN_ROOT%/bin
- '%CYGWIN_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./scallywag"'
cache:
- C:\cache
artifacts:
- path: staging
  name: artifacts
test: off
notifications:
  provider: Webhook
  url: http://cygwin.com/cgi-bin2/hook.cgi
  headers:
    Authorization:
      secure: r9DfPVTZOdxGpZzS/vm4Ew==
