version: '{build}'
clone_depth: 1
image: Visual Studio 2019
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  CYGWIN_MIRROR: http://cygwin.mirror.constant.com
  CACHE: C:\cache
  matrix:
  - BUILD: x86_64-pc-cygwin
install:
- set CYGWIN_ROOT=C:\cygwin64
- set SETUP=%CYGWIN_ROOT%\setup-x86_64.exe
- curl -fsSL https://gist.githubusercontent.com/jon-turney/0338af595313f598bfab15a0ac0df847/raw/bd0eeca6be899e7846aa988fbcf15e4e12f5f842/zp_libtool_cleanlafiles.sh -o %CYGWIN_ROOT%\etc\postinstall\zp_libtool_cleanlafiles.sh
- echo Updating Cygwin
- '%SETUP% -qnNdO -R %CYGWIN_ROOT% -s %CYGWIN_MIRROR% -l %CACHE% -g -P cygport,lzip,python3'
build_script:
- SET ORIG_PATH=%PATH%
- SET PATH=%CYGWIN_ROOT%/bin
- '%CYGWIN_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./scallywag"'
cache:
- C:\cache
artifacts:
- path: staging
  name: artifacts
on_finish:
- SET PATH=%ORIG_PATH%
- appveyor PushArtifact builddir.tar.xz -DeploymentName builddir || true
test: off
notifications:
  provider: Webhook
  url: https://cygwin.com/cgi-bin2/hook.cgi
  headers:
    Authorization:
      secure: r9DfPVTZOdxGpZzS/vm4Ew==
