#!/bin/sh
set -e

tmpfile=$(mktemp)
wget -nv $3 -O ${tmpfile}
unzip -o ${tmpfile} -d "/sourceware/cygwin-staging/home/$1/$2/release"
rm ${tmpfile}

#touch "/sourceware/cygwin-staging/home/$1/$2/release/!ready"
#kill -SIGUSR1 $(cat /sourceware/cygwin-staging/calm.pid)
