#!/usr/bin/env python3
#
# post-receive hook to start a package build
#

import os
import sys

from request_build import request_build
from utils import get_maintainer

if __name__ == '__main__':
    if 'GL_REPO' in os.environ:
        # set by gitolite
        repo = os.environ['GL_REPO']
    else:
        # otherwise, assume repository is the working directory
        repo = os.getcwd()

    maintainer = get_maintainer()

    print('scallywag: invoked on repository {0}, by maintainer {1}'.format(repo, maintainer))

    tokens = ''
    for i in range(0, int(os.environ.get('GIT_PUSH_OPTION_COUNT', '0'))):
        print('%s: %s' % ('GIT_PUSH_OPTION_%s' % i, os.environ['GIT_PUSH_OPTION_%s' % i]))
        tokens += ' ' + os.environ['GIT_PUSH_OPTION_%s' % i].strip()

    _, package = os.path.split(repo)
    if package.endswith('.git'):
        package, _ = os.path.splitext(package)

    for line in sys.stdin.readlines():
        old, new, ref = line.strip().split()
        if ref.startswith('refs/heads/') and new != '0000000000000000000000000000000000000000':
            # only do something if a branch ref is updated
            request_build(new, ref, package, maintainer, tokens)
