#!/usr/bin/env python3
#
# start a package build, to rerun a job
#

import argparse
import sqlite3

import carpetbag
from request_build import request_build


def rerun(id, tokens):
    with sqlite3.connect(carpetbag.dbfile) as conn:
        conn.row_factory = sqlite3.Row
        cursor = conn.execute('SELECT * FROM jobs WHERE id = ?', (id,))
        row = cursor.fetchone()

    commit = row['hash']
    ref = row['ref']
    package = row['srcpkg']
    maintainer = row['user']

    print(commit, ref, package, maintainer, tokens)
    request_build(commit, ref, package, maintainer, tokens)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Re-run job')
    parser.add_argument('id', metavar='ID', type=int, help='job id')
    parser.add_argument('--token', metavar='TOKEN', action='append', help='job id', default=[])
    args = parser.parse_args()

    rerun(args.id, ' '.join(args.token))
