#!/usr/bin/env python3

import argparse
import glob
import json
import logging
import os
import shutil
import subprocess
import sys
import urllib.error
import urllib.request

from analyze import analyze

logging.getLogger().setLevel(logging.INFO)
logging.basicConfig(format=os.path.basename(sys.argv[0]) + ': %(message)s')

parser = argparse.ArgumentParser(description='scallywag')
parser.add_argument('--inputs', dest='inputs', action='store', help='JSON encoded input parameters')
args = parser.parse_args()

if args.inputs:
    args_dict = json.loads(args.inputs)
    logging.info('input args are %s' % (args_dict))
else:
    args_dict = os.environ

buildnumber = args_dict['BUILDNUMBER']
name = args_dict['PACKAGE']
maintainer = args_dict['MAINTAINER']
commit = args_dict['COMMIT']
reference = args_dict['REFERENCE']
default_tokens = args_dict.get('DEFAULT_TOKENS', '')

arch = os.environ['BUILD'].split('-')[0]

logging.info('package is %s' % (name))

# make a directory for working with the package repo
mydir = os.getcwd()
os.chdir(os.path.join(mydir, '..'))
os.mkdir(name)
os.chdir(name)
workdir = os.getcwd()

if (arch == 'source') or ('APPVEYOR' in os.environ):
    # clone the package repo
    # 'git clone' can't do a shallow clone of a specific commit.
    #
    # (This requires allowReachableSHA1InWant to be true at the remote, to allow
    # non-branch/tag tip commits to be fetched)
    try:
        logging.info('cloning the packaging repository')
        subprocess.check_call(['git', 'config', '--global', 'init.defaultBranch', 'master'])
        subprocess.check_call(['git', 'init'])
        subprocess.check_call(['git', 'remote', 'add', 'origin', 'git://cygwin.com/git/cygwin-packages/%s.git' % (name)])
        subprocess.check_call(['git', 'fetch', '--depth=1', 'origin', commit])
        subprocess.check_call(['git', 'checkout', '-B', 'master', 'FETCH_HEAD'])
        subprocess.check_call(['git', 'submodule', 'update', '--init', '--recursive'])
        # Using '--depth=1' with a submodule will fail if the remote doesn't have
        # allowReachableSHA1InWant set.  If it does, the submodule should be
        # configured as shallow in .gitmodules, so '--recommend-shallow' turns that
        # on.
    except (subprocess.CalledProcessError, FileNotFoundError):
        logging.info('something went wrong cloning the packaging repository')
        sys.exit(1)
else:
    # unpack the source package
    # use '--strip-components' option to drop leading 'P-V-R.src/'
    try:
        logging.info('unpacking the source package')
        subprocess.check_call('tar -C %s --strip-components=1 -Jxvf %s' % (workdir,
                                                                           os.path.join(mydir, 'srcpkg', '*', '*-*-src.tar.xz')),
                              shell=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        logging.info('something went wrong unpacking the source package')
        sys.exit(1)

# analyze the source
package = analyze(workdir, default_tokens.split())

# compare target arch(es) and build environment
logging.info('build ARCH: %s, cygport ARCHes: %s' % (arch, package.arches))

if ('noarch' in package.arches) and ('APPVEYOR' in os.environ):
    # noarch packages get built using x86_64 environment on AppVeyor
    if arch == 'x86_64':
        arch = 'noarch'
    else:
        arch = 'skip'
elif package.arches:
    # otherwise, build if it builds on this environment
    if arch not in package.arches + ['source']:
        arch = 'skip'
else:
    logging.info('arch(es) to build for could not be determined')
    sys.exit(1)

data_items = {
    'BUILDNUMBER': buildnumber,
    'PACKAGE': name,
    'COMMIT': commit,
    'ARCH': arch,
    'MAINTAINER': maintainer,
    'REFERENCE': reference,
    'TOKENS': (' '.join(package.tokens)),
    'ANNOUNCE': package.announce,
}

if 'APPVEYOR' in os.environ:
    # record package details using build worker API (so they appear in build notification)
    data = {"message": '; '.join('%s: %s' % (k, v) for k, v in data_items.items())}
    req = urllib.request.Request(os.environ['APPVEYOR_API_URL'] + 'api/build/messages')
    req.add_header('Content-Type', 'application/json')
    response = urllib.request.urlopen(req, json.dumps(data).encode('utf-8'))
elif 'GITHUB_JOB' in os.environ:
    # record package details in .json file
    with open(os.path.join(mydir, 'scallywag.json'), 'w') as f:
        print(json.dumps(data_items, sort_keys=True, indent=4), file=f)

if arch == 'skip':
    logging.info('nothing to build on this arch')
    sys.exit(0)

if 'nobuild' in package.tokens:
    logging.info('not building due to nobuild')
    sys.exit(0)

setup_exe = subprocess.check_output(['cygpath', os.environ['SETUP']]).strip()

if package.kind == 'cygport':
    logging.info('installing build dependencies')

    setup_opts = []
    if 'testpackages' in package.tokens:
        setup_opts.append('-t')

    subprocess.check_call([setup_exe,
                           '-q', '-n', '-O'] + setup_opts +
                          ['-R', os.environ['CYGWIN_ROOT'],
                           '-s', os.environ['CYGWIN_MIRROR'],
                           '-l', os.environ['CACHE'],
                           '-P', ','.join(package.depends)])

    # preserve setup.log.full
    shutil.move('/var/log/setup.log.full', os.path.join(mydir, 'setup.log.full'))

    # assemble the series of cygoprt subcommands for the build
    subcommands = []

    if arch != 'source':
        # no separate source package stage on AppVeyor, so fetch upstream sources
        if 'APPVEYOR' in os.environ:
            subcommands.append('download')

        if 'label' in package.tokens:
            subcommands.append('all-test')
        else:
            subcommands.append('all')

        if 'notest' not in package.tokens:
            subcommands.append('test')
    else:
        subcommands.append('download prep')

        if 'label' in package.tokens:
            subcommands.append('srcpackage-test')
        else:
            subcommands.append('srcpackage')

    logging.info("running 'cygport %s'" % (' '.join(subcommands)))
    rc = subprocess.call([os.path.join(mydir, 'build.sh'), package.script] +
                         subcommands, stdin=subprocess.DEVNULL)

    # publish contents of dist as artifacts
    dist = glob.glob(os.path.join('*', 'dist'))
    if dist:
        logging.info('publishing artifacts')
        stagingdir = os.path.join(mydir, 'staging')
        shutil.move(dist[0], stagingdir)
        for (dirpath, _, files) in os.walk(stagingdir):
            for f in files:
                # since cygport currently lacks a command to produce the install
                # package only, we use 'all' above and filter out the source
                # package here
                if 'APPVEYOR' not in os.environ:
                    if ('-src.' in f) != (arch == 'source'):
                        os.remove(os.path.join(dirpath, f))
                        continue

                logging.info(os.path.relpath(os.path.join(dirpath, f), mydir))

    # publish an archive with contents of builddir
    subprocess.check_call('tar -Jcf %s *' % (os.path.join(mydir, 'builddir.tar.xz')),
                          shell=True)

    sys.exit(rc)
else:
    logging.info("don't know how to build this package")
    sys.exit(1)
