name: scallywag

on:
  workflow_dispatch:
    inputs:
      payload:
        description: json-encoded payload
        required: true
      title:
        description: title in UI
        required: true

run-name: "${{ inputs.title }}"

# set restricted permissions for GITHUB_TOKEN
permissions:
  contents: read

jobs:
  source:
    uses: ./.github/workflows/build.yml
    with:
      name: source

  x86_64:
    needs: source

    uses: ./.github/workflows/build.yml
    with:
      name: x86_64

    if: ${{ contains(needs.source.outputs.arches, 'x86_64') }}

  aarch64:
    needs: source

    uses: ./.github/workflows/crossbuild.yml
    with:
      name: aarch64
      pkgarch: '-aarch64'

    if: ${{ contains(needs.source.outputs.arches, 'aarch64') }}

  noarch:
    needs: source

    uses: ./.github/workflows/build.yml
    with:
      name: noarch

    if: ${{ contains(needs.source.outputs.arches, 'noarch') }}
