name: scallywag
on:
  - repository_dispatch

# set restricted permissions for GITHUB_TOKEN
permissions:
  contents: read

jobs:
  source:
    uses: ./.github/workflows/build.yml
    with:
      name: source

  x86_64:
    needs: source

    uses: ./.github/workflows/build.yml
    with:
      name: x86_64

  noarch:
    needs: source

    uses: ./.github/workflows/build.yml
    with:
      name: noarch
